/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_douglasrivera;

import javax.swing.JOptionPane;

/**
 *
 * @author famii
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_LogIn = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        jbEntrar = new javax.swing.JButton();
        jbSign = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCEO = new javax.swing.JMenu();
        JmiCEO_LogIn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmAdministrativos = new javax.swing.JMenu();
        jmiAdm_LogIn = new javax.swing.JMenuItem();
        IDocentes = new javax.swing.JMenuItem();
        jmPersonal = new javax.swing.JMenu();
        jmiPer_LogIn = new javax.swing.JMenuItem();
        IEstudiantes = new javax.swing.JMenuItem();
        ITutores = new javax.swing.JMenuItem();
        jmConsejo = new javax.swing.JMenu();
        jmiCons_LogIn = new javax.swing.JMenuItem();
        jmi_Consejo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Sistema de Inicio de Sesión");

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Contraseña:");

        txtPass.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N

        txtUser.setFont(new java.awt.Font("Segoe UI Symbol", 1, 48)); // NOI18N

        jbEntrar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jbEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member.png"))); // NOI18N
        jbEntrar.setText("Entrar");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });

        jbSign.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jbSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member-add.png"))); // NOI18N
        jbSign.setText("Sign Up");
        jbSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSign)
                        .addGap(152, 152, 152)
                        .addComponent(jbEntrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPass)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_LogInLayout = new javax.swing.GroupLayout(jd_LogIn.getContentPane());
        jd_LogIn.getContentPane().setLayout(jd_LogInLayout);
        jd_LogInLayout.setHorizontalGroup(
            jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LogInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jd_LogInLayout.setVerticalGroup(
            jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("UNITEC");

        jmCEO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member.png"))); // NOI18N
        jmCEO.setText("CEO");

        JmiCEO_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member-add.png"))); // NOI18N
        JmiCEO_LogIn.setText("Log In");
        JmiCEO_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCEO_LogInActionPerformed(evt);
            }
        });
        jmCEO.add(JmiCEO_LogIn);

        jMenuItem1.setText("Listado");
        jMenuItem1.setEnabled(false);
        jmCEO.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.setEnabled(false);
        jmCEO.add(jMenuItem2);

        jMenu1.add(jmCEO);

        jmAdministrativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member.png"))); // NOI18N
        jmAdministrativos.setText("Administrativos");

        jmiAdm_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member-add.png"))); // NOI18N
        jmiAdm_LogIn.setText("Log In");
        jmiAdm_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdm_LogInActionPerformed(evt);
            }
        });
        jmAdministrativos.add(jmiAdm_LogIn);

        IDocentes.setText("Docentes");
        IDocentes.setEnabled(false);
        jmAdministrativos.add(IDocentes);

        jMenu1.add(jmAdministrativos);

        jmPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member.png"))); // NOI18N
        jmPersonal.setText("Personales de Planta");

        jmiPer_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member-add.png"))); // NOI18N
        jmiPer_LogIn.setText("Log In");
        jmiPer_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPer_LogInActionPerformed(evt);
            }
        });
        jmPersonal.add(jmiPer_LogIn);

        IEstudiantes.setText("Estudiantes");
        IEstudiantes.setEnabled(false);
        jmPersonal.add(IEstudiantes);

        ITutores.setText("Tutores");
        ITutores.setEnabled(false);
        jmPersonal.add(ITutores);

        jMenu1.add(jmPersonal);

        jmConsejo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member.png"))); // NOI18N
        jmConsejo.setText("Consejo Academicos");

        jmiCons_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24-member-add.png"))); // NOI18N
        jmiCons_LogIn.setText("Log In");
        jmiCons_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCons_LogInActionPerformed(evt);
            }
        });
        jmConsejo.add(jmiCons_LogIn);

        jmi_Consejo.setText("Consejo");
        jmi_Consejo.setEnabled(false);
        jmConsejo.add(jmi_Consejo);

        jMenu1.add(jmConsejo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("HELP");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        if(txtUser.getText() == null || "".equals(txtUser.getText())){
            JOptionPane.showMessageDialog(this, "Ingresar un usuario: ");
        }
        if(txtPass.getText() == null || "".equals(txtPass.getText())){
            JOptionPane.showMessageDialog(this, "Ingresar una contraseña: ");
        }
        if(txtUser.getText().equals("OsmanMejia69") && txtPass.getText().equals("Omejia")){
        }else{
            JOptionPane.showMessageDialog(this, "Ingresar el usuario o contraseña correctos: ");
        }
    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jbSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSignActionPerformed
        this.dispose();
        new FormularioAdmin().setVisible(true);
    }//GEN-LAST:event_jbSignActionPerformed

    private void JmiCEO_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCEO_LogInActionPerformed
       MostrarLogin();
    }//GEN-LAST:event_JmiCEO_LogInActionPerformed

    private void jmiAdm_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdm_LogInActionPerformed
        MostrarLogin();
    }//GEN-LAST:event_jmiAdm_LogInActionPerformed

    private void jmiPer_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPer_LogInActionPerformed
        MostrarLogin();
    }//GEN-LAST:event_jmiPer_LogInActionPerformed

    private void jmiCons_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCons_LogInActionPerformed
        MostrarLogin();
    }//GEN-LAST:event_jmiCons_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    public void MostrarLogin(){
        jd_LogIn.setModal(true);
        jd_LogIn.pack();
        jd_LogIn.setLocationRelativeTo(this);
        jd_LogIn.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IDocentes;
    private javax.swing.JMenuItem IEstudiantes;
    private javax.swing.JMenuItem ITutores;
    private javax.swing.JMenuItem JmiCEO_LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JButton jbSign;
    private javax.swing.JDialog jd_LogIn;
    private javax.swing.JMenu jmAdministrativos;
    private javax.swing.JMenu jmCEO;
    private javax.swing.JMenu jmConsejo;
    private javax.swing.JMenu jmPersonal;
    private javax.swing.JMenuItem jmiAdm_LogIn;
    private javax.swing.JMenuItem jmiCons_LogIn;
    private javax.swing.JMenuItem jmiPer_LogIn;
    private javax.swing.JMenuItem jmi_Consejo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
